name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  test-github:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7', '1.10']
        julia-arch: [x64]
        os: [ubuntu-latest,macos-13,windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest 
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3.1.1
        with:
          file: lcov.info
